export const cityList = [
    { name: "Jakarta", code: "JK", province: "DKI Jakarta" },
    { name: "Surabaya", code: "SBY", province: "Jawa Timur" },
    { name: "Bandung", code: "BDG", province: "Jawa Barat" },
    { name: "Medan", code: "MDN", province: "Sumatera Utara" },
    { name: "Semarang", code: "SMG", province: "Jawa Tengah" },
    { name: "Makassar", code: "MKS", province: "Sulawesi Selatan" },
    { name: "Denpasar", code: "DPS", province: "Bali" },
    { name: "Yogyakarta", code: "YGY", province: "DI Yogyakarta" },
    { name: "Palembang", code: "PLB", province: "Sumatera Selatan" },
    { name: "Balikpapan", code: "BPP", province: "Kalimantan Timur" },
    { name: "Malang", code: "MLG", province: "Jawa Timur" },
    { name: "Padang", code: "PDG", province: "Sumatera Barat" },
    { name: "Pontianak", code: "PTK", province: "Kalimantan Barat" },
    { name: "Banjarmasin", code: "BJM", province: "Kalimantan Selatan" },
    { name: "Pekanbaru", code: "PKU", province: "Riau" },
    { name: "Manado", code: "MDO", province: "Sulawesi Utara" },
    { name: "Mataram", code: "MTR", province: "Nusa Tenggara Barat" },
    { name: "Samarinda", code: "SMD", province: "Kalimantan Timur" },
    { name: "Jambi", code: "JMB", province: "Jambi" },
    { name: "Ambon", code: "AMB", province: "Maluku" },
    { name: "Ternate", code: "TNT", province: "Maluku Utara" },
    { name: "Jayapura", code: "JYP", province: "Papua" },
    { name: "Kupang", code: "KPG", province: "Nusa Tenggara Timur" },
    { name: "Palu", code: "PLU", province: "Sulawesi Tengah" },
    { name: "Gorontalo", code: "GTO", province: "Gorontalo" },
    { name: "Banda Aceh", code: "BNA", province: "Aceh" },
    { name: "Serang", code: "SRG", province: "Banten" },
    { name: "Tasikmalaya", code: "TSM", province: "Jawa Barat" },
    { name: "Cirebon", code: "CBN", province: "Jawa Barat" },
    { name: "Magelang", code: "MGL", province: "Jawa Tengah" },
    { name: "Kediri", code: "KDR", province: "Jawa Timur" },
    { name: "Tegal", code: "TGL", province: "Jawa Tengah" },
    { name: "Probolinggo", code: "PBL", province: "Jawa Timur" },
    { name: "Bogor", code: "BGR", province: "Jawa Barat" },
    { name: "Depok", code: "DPK", province: "Jawa Barat" },
    { name: "Bekasi", code: "BKS", province: "Jawa Barat" },
    { name: "Tangerang", code: "TNG", province: "Banten" },
    { name: "Batam", code: "BTM", province: "Kepulauan Riau" },
    { name: "Pangkal Pinang", code: "PKP", province: "Bangka Belitung" },
  ];
  